rootProject.name = "kuke-board"

include("common")
include("common:snowflake")
include("common:jpa")
include("common:pagination")
include("common:serialization")
include("common:event")
include("common:outbox")
include("service")
include("service:article")
include("service:comment")
include("service:view")
include("service:like")
include("service:hot-article")
include("service:article-read")
include("service:user")
include("service:gateway")
